---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages' ]
      
- include: control.yaml
- include: database.yaml
- include: webserver.yaml
- include: loadbalancer.yaml