---
- hosts: controller
  become: true
  tasks: 
    - name: install tools
      apt: name={{item}} state=present
      #apt: name={{item}} state=present update_cache=yes
      with_items:
        - curl
        - python-httplib2

    - name: get hostname  
      command: hostname
      register: result
      changed_when: result.rc != 0